### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'post' of null

### ISSUE THREAD

**Issue by Hidend** [nelu/rutorrent-filemanager-share#1]
I'm getting this all of the sudden, any ideas of what can it be?
JS error: [https://torrent.domain.com/ : 3161] Uncaught TypeError: Cannot read property 'post' of null

I'm getting it when I just open fileshare tab, no problems with fileshare-media or filemanager

I guess it comes from here:
https://github.com/nelu/rutorrent-filemanager-share/blob/ab48f2c6ced361fc8f56c13f315327959c68ee9e/init.js#L194

And somehow this fails? https://github.com/nelu/rutorrent-filemanager-share/blob/ab48f2c6ced361fc8f56c13f315327959c68ee9e/init.js#L235

**Comment by Phil2812** [comment]
This can be fixed by setting your language to English or editing the `lang/<language code>.js` to match the contents of https://github.com/nelu/rutorrent-filemanager-share/blob/master/lang/en.js

Make sure to cache-clearing reload the language file afterwards.

**Comment by nelu** [comment]
All translation files will be needing at the end of file

`thePlugins.get("filemanager-share").langLoaded(); `

**Comment by nelu** [comment]
Fixed in commit: https://github.com/nelu/rutorrent-filemanager-share/commit/7d7c406c80da2690087d83f1c21777730200f394

**Comment by jegue** [comment]
> This can be fixed by setting your language to English or editing the `lang/<language code>.js` to match the contents of https://github.com/nelu/rutorrent-filemanager-share/blob/master/lang/en.js
> 
> Make sure to cache-clearing reload the language file afterwards.

how to set to always in English?
thanks
